const cream = [
    {
        id: '1',
        flavor: 'Abacate',
        price: 3.5,
        quantity: 0,
        uri: 'https://i.imgur.com/txYwunQ.png',
    },
    {
        id: '2',
        flavor: 'Abacate com Paçoca',
        price: 3.5,
        quantity: 0,
        uri: 'https://i.imgur.com/p1GMD83.png',
    },
    {
        id: '3',
        flavor: 'Açaí com Paçoça',
        price: 3.5,
        quantity: 0,
        uri: 'https://i.imgur.com/OOEM7zB.png',
    },
    {
        id: '4',
        flavor: 'Bis',
        price: 3.5,
        quantity: 0,
        uri: 'https://i.imgur.com/puU7WXo.jpg',
    },
    {
        id: '5',
        flavor: 'Blue Ice',
        price: 3.5,
        quantity: 0,
        uri: 'https://i.imgur.com/Yfx5555.jpg',
    },
    {
        id: '6',
        flavor: 'Brigadeiro',
        price: 3.5,
        quantity: 0,
        uri: 'https://i.imgur.com/xb8v8sx.jpg',
    },
    {
        id: '7',
        flavor: 'Coco',
        price: 3.5,
        quantity: 0,
        uri: 'https://i.imgur.com/pp5oxPG.png',
    },
    {
        id: '8',
        flavor: 'Coco Queimando',
        price: 3.5,
        quantity: 0,
        uri: 'https://i.imgur.com/7QTIAVm.png',
    },
    {
        id: '9',
        flavor: 'Chocomenta',
        price: 4.5,
        quantity: 0,
        uri: 'https://i.imgur.com/GjAYLPO.jpg',
    },
    {
        id: '10',
        flavor: 'Cupuaçu',
        price: 3.5,
        quantity: 0,
        uri: 'https://i.imgur.com/h63t19o.jpg',
    },
    {
        id: '11',
        flavor: 'Cupuaçu com Chocolate',
        price: 3.5,
        quantity: 0,
        uri: 'https://i.imgur.com/HjqmE8A.png',
    },
    {
        id: '12',
        flavor: 'Cupuaçu com Morango',
        price: 3.5,
        quantity: 0,
        uri: 'https://i.imgur.com/jvPxrPA.png',
    },
    {
        id: '13',
        flavor: 'Mousse de Abacaxi',
        price: 3.5,
        quantity: 0,
        uri: 'https://i.imgur.com/jvPxrPA.png',
    },
    {
        id: '14',
        flavor: 'Mousse de Limão',
        price: 3.5,
        quantity: 0,
        uri: 'https://i.imgur.com/1CE952E.png',
    },
    {
        id: '15',
        flavor: 'Mousse de Maracujá',
        price: 3.5,
        quantity: 0,
        uri: 'https://i.imgur.com/u4Xo4l1.png',
    },
    {
        id: '16',
        flavor: 'Morango com Nutella',
        price: 4.5,
        quantity: 0,
        uri: 'https://i.imgur.com/jvPxrPA.png',
    },
    {
        id: '17',
        flavor: 'Ninho com Nutella',
        price: 3.5,
        quantity: 0,
        uri: 'https://i.imgur.com/NCWdeB8.png',
    },
    {
        id: '18',
        flavor: 'Ninho com Morango',
        price: 4.5,
        quantity: 0,
        uri: 'https://i.imgur.com/Uc1JHwi.png',
    },
    {
        id: '19',
        flavor: 'Oreo',
        price: 3.5,
        quantity: 0,
        uri: 'https://i.imgur.com/fpemqHd.jpg',
    },
    {
        id: '20',
        flavor: 'Ouro Branco',
        price: 3.5,
        quantity: 0,
        uri: 'https://i.imgur.com/yfLiJNk.jpg',
    },
    {
        id: '21',
        flavor: 'Ovomaltine',
        price: 3.5,
        quantity: 0,
        uri: 'https://i.imgur.com/7yoeaBO.png',
    },
    {
        id: '22',
        flavor: 'Prestígio',
        price: 3.5,
        quantity: 0,
        uri: 'https://i.imgur.com/iF10uoC.png',
    },
    {
        id: '23',
        flavor: 'Sonho de Valsa',
        price: 3.5,
        quantity: 0,
        uri: 'https://i.imgur.com/LKphmh2.jpg',
    },
    {
        id: '24',
        flavor: 'Uva Passa',
        price: 3.5,
        quantity: 0,
        uri: 'https://i.imgur.com/rtaxYkB.jpg',
    },
    {
        id: '25',
        flavor: 'Limão Trufado',
        price: 4.5,
        quantity: 0,
        uri: 'https://i.imgur.com/jvPxrPA.png',
    },
    {
        id: '26',
        flavor: 'Maracujá Trufado',
        price: 4.5,
        quantity: 0,
        uri: 'https://i.imgur.com/jvPxrPA.png',
    },
    {
        id: '27',
        flavor: 'Morango Trufado',
        price: 4.5,
        quantity: 0,
        uri: 'https://i.imgur.com/jvPxrPA.png',
    },
    {
        id: '28',
        flavor: 'Ninho Trufado',
        price: 4.5,
        quantity: 0,
        uri: 'https://i.imgur.com/jvPxrPA.png',
    },
];

export default cream;
